remote_theme: ankitsultana/researcher@gem
title: Xiao Li (李啸)
url: "https://xiaoli0614.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

#tracking_id: UA-191973079-1

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
